version: '3.1'
services:
  goodline_ip:
    image: 'docker.sadovskiy.net/goodline_iptv:latest'
    restart: always
    environment:
      LOG_LEVEL: 3
    volumes:
      - './iptv:/var/lib/goodline_iptv'
